server:
  port: 8080
spring:
  jackson:
    date-format: dd-MM-yyyy HH:mm:ss
  application:
    name: kaawa
  datasource:
    password: password
    username: postgres
    url: jdbc:postgresql://localhost:5432/kaawa
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  mail:
    host: mail.gmx.com
    port: 587
    username: projetkawaa@gmx.fr
    password: Projet_Kawaa!20231031
    default-encoding: UTF-8
    properties:
      mail:
        mine:
          charset: UTF
        smtp:
          write-timeout: 10000
          connection-timeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
        debug: true
    verify:
      host: projetkawaa@gmail.com
application:
  firebase:
    bucket-name: projetkawaa-62901.appspot.com
    project-id: projetkawaa-62901
    json-file: firebase.json